### ISSUE TITLE
Even / odd classes for filtered elements

### ISSUE THREAD

**Issue by dgorges** [javve/list.js#302]
It would be nice to add classes for styling even or odd filtered elements.

**Comment by javve** [comment]
Just use CSS3
```css
tr:nth-child(even) {
  background: #ccc;
}
tr:nth-child(odd) {
  background: #fff;
}
```
It works for almost everyone expect IE8 and I don't expect them to expect graphical details :grin:
